MDScreen:
    name : 'splash'

    MDFloatLayout:

        md_bg_color: '#b613c0'

        Image:
            source:'assets/logo.png'
            size_hint: .26, .26
            pos_hint:{'center_x':.5, 'center_y':.48}
            canvas.before:
                Color:
                    rgb:1,1,1,1
                Ellipse:
                    size: 130, 130
                    pos: 110, 250

